# Don't run build jobs for branches
trigger:
  batch: true

# Still allow PR builds to run against master
pr:
- master

jobs:
  - template: ./.azure-pipelines/azure-pipelines-linux.yml
  - template: ./.azure-pipelines/azure-pipelines-osx.yml
