{% set name = "mmdb2" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.ccp4.ac.uk/opensource/{{ name }}-{{ version }}.tar.gz
  sha256: 7be92fa9348c83384111687e8e093dcc92f609e6caaad78f6275317aa0de1320

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make


about:
  home: http://fg.oisin.rc-harwell.ac.uk/projects/mmdb2/
  summary: 'CCP4 Coordinate Library: support of coordinate-related functionality in protein crystallography applications.'
  license: LGPL-3.0-only
  license_family: LGPL
  license_file:
    - COPYING.LESSER
    - COPYING

extra:
  recipe-maintainers:
    - ndevenish