{% set name = "mmdb2" %}
{% set version = "2.0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ndevenish/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4529a4078dd7da1adbb2432bbb62b47911bffbd72cae4ec02042d52c4f03330a

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

about:
  home: http://fg.oisin.rc-harwell.ac.uk/projects/mmdb2/
  summary: 'CCP4 Coordinate Library: support of coordinate-related functionality in protein crystallography applications.'
  license: LGPL-3.0-only
  license_family: LGPL
  license_file:
    - libccp4/trunk/COPYING.LESSER
    - libccp4/trunk/COPYING

extra:
  recipe-maintainers:
    - ndevenish