{% set name = "rtoml" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rtoml-{{ version }}.tar.gz
  sha256: 6d55fa9df88256c6762f01f18b8bd3f6dc1836600ea8655eb3719a2b8f3df764

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
  host:
    - libgcc-ng  # [linux]
    - pip >=21.0.1
    - python >=3.7
    - setuptools-rust
  run:
    - python >=3.7

test:
  imports:
    - rtoml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/samuelcolvin/rtoml
  summary: A better TOML library for python implemented in rust.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AhmedAliStats
