# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
# If your package is python based, we recommend using Grayskull to generate it instead:
# https://github.com/conda-incubator/grayskull

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "nuweb" %}
{% set version = "1.62" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/{{ name }}/files/{{ name }}-{{ version }}.tar.gz
  sha256: 255a8f62460f5c14f4c4b356b96e0357a37a6652ae0584064f8e9fae19e953ae

build:
  script: |
    make nuweb CC=$CC
    mkdir -p $PREFIX/bin
    cp nuweb $PREFIX/bin/nuweb
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - nuweb -h

about:
  home: http://nuweb.sourceforge.net/
  summary: 'nuweb for Literate Programming'
  description: |
    In 1984, Knuth introduced the idea of literate programming. The idea
    was that a programmer wrote one document, the web file, that
    combined documentation with code. Nuweb works with any programming
    language and LaTeX.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://sourceforge.net/projects/nuweb/

extra:
  recipe-maintainers:
    - ndevenish
