{% set name = "libccp4" %}
{% set version = "8.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.ccp4.ac.uk/opensource/{{ name }}-{{ version }}.tar.gz
  sha256: cb813ae86612a0866329deab7cee96eac573d81be5b240341d40f9ad5322ff2d

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - m4
    - mmdb2
  host:
    - mmdb2

about:
  home: http://fg.oisin.rc-harwell.ac.uk/projects/libccp4/
  summary: 'libccp4'
  description: |
    simplejson is a simple, fast, complete, correct and extensible
    JSON <https://json.org> encoder and decoder for Python 2.5+ and
    Python 3.3+. It is pure Python code with no dependencies, but includes
    an optional C extension for a serious speed boost.
  license: LGPL-3.0-only
  license_family: LGPL
  license_file:
    - COPYING.LESSER
    - COPYING

extra:
  recipe-maintainers:
    - ndevenish