{% set name = "libccp4" %}
{% set version = "8.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ndevenish/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 298d1517723d95548c3d916c326d8054b2fa1e11b2a5e44822fe7a2bada50178

build:
  number: 0

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
    - cmake

about:
  home: http://fg.oisin.rc-harwell.ac.uk/projects/libccp4/
  summary: 'libccp4'
  description: |
    simplejson is a simple, fast, complete, correct and extensible
    JSON <https://json.org> encoder and decoder for Python 2.5+ and
    Python 3.3+. It is pure Python code with no dependencies, but includes
    an optional C extension for a serious speed boost.
  license: LGPL-3.0-only
  license_family: LGPL
  license_file:
    - libccp4/trunk/COPYING.LESSER
    - libccp4/trunk/COPYING

extra:
  recipe-maintainers:
    - ndevenish