{% set name = "xia2" %}
{% set version = "3.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/xia2/xia2/archive/v{{ version }}.tar.gz
  # sha256: 6663c07e6221b2e25e5023d076ded81f3b093926ae30c408bd39336fe3120638
  git_url: https://github.com/xia2/xia2.git
  git_rev: main

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - dev.xia2.check_mosaic=xia2.cli.check_mosaic:run
    - dev.xia2.create_mask=xia2.cli.create_mask:run
    - dev.xia2.file_statistics=xia2.cli.file_statistics:run
    - dev.xia2.make_sphinx_html=xia2.cli.make_sphinx_html:run
    - dev.xia2.show_mask=xia2.cli.show_mask:run
    - dev.xia2.show_mtz_cells=xia2.cli.show_mtz_cells:run
    - xia2.add_free_set=xia2.cli.add_free_set:run
    - xia2.compare_merging_stats=xia2.cli.compare_merging_stats:run
    - xia2.delta_cc_half=xia2.cli.delta_cc_half:run
    - xia2.get_image_number=xia2.cli.get_image_number:run
    - xia2.html=xia2.cli.xia2_html:run_with_log
    - xia2.index=xia2.cli.index:run_with_log
    - xia2.integrate=xia2.cli.integrate:run_with_log
    - xia2.is_doing=xia2.cli.is_doing:main
    - xia2.ispyb_json=xia2.cli.ispyb_json:run
    - xia2.ispyb_xml=xia2.cli.ispyb_xml:run
    - xia2.merging_statistics=xia2.cli.merging_statistics:run
    - xia2.multi_crystal_analysis=xia2.cli.multi_crystal_analysis:run_with_log
    - xia2.multiplex=xia2.cli.multiplex:run
    - xia2.npp=xia2.cli.npp:run
    - xia2.overload=xia2.cli.overload:run
    - xia2.plot_multiplicity=xia2.cli.plot_multiplicity:run
    - xia2.print=xia2.cli.print:run_with_log
    - xia2.rebatch=xia2.cli.rebatch:run_with_log
    - xia2.report=xia2.cli.report:run_with_log
    - xia2.rescale=xia2.cli.rescale:run_with_log
    - xia2.setup=xia2.cli.setup:run
    - xia2.small_molecule=xia2.cli.small_molecule:run
    - xia2.strategy=xia2.cli.strategy:run_with_log
    - xia2.table1=xia2.cli.table1:run
    - xia2.to_shelx=xia2.cli.to_shelx:run
    - xia2.to_shelxcde=xia2.cli.to_shelxcde:run
    - xia2=xia2.cli.xia2_main:run

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dials

test:
  source_files:
    - tests
    - conftest.py
  imports:
    - xia2
  requires:
    - pip
    - pytest
    - dials-data
    - pytest-mock
  commands:
    - pip check
    - pytest $SRC_DIR/tests  # [not win]
    - pytest %SRC_DIR%/tests  # [win]

about:
  home: https://github.com/xia2/xia2
  summary: 'An expert system for automated reduction of X-Ray diffraction data from macromolecular crystals'
  description: |
    xia2 is an expert system to perform X-ray diffraction data processing on
    your behalf, using your software with little or no input from you. It will
    correctly handle multi-pass, multi-wavelength data sets as described later
    but it is not a data processing package. Specifically, if you use xia2 in
    published work please include the references for the programs it has used,
    which are printed at the end of the output. The system was initially
    written to support remote access to synchrotron facilities, however it may
    prove useful to anyone using MX, for example:

    - assisting new or novice users,
    - giving a second opinion to experts,
    - assisting busy users to allow them to focus on problem cases, or
    - providing reproducible processing.

    The last of these may be most useful for users in a pharmaceutical setting,
    or people wishing to test or benchmark equipment, for example beamline
    scientists. In all cases however the usage of the program is the same.
  license: BSD-3-Claise
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ndevenish
    - rjgildea
